services:
  api:
    image: ne1i/pixels_site-api:latest
    restart: unless-stopped
    environment:
      CanvasConfig__Width: 1000
      CanvasConfig__Height: 1000
      CanvasConfig__SavePath: /data/canvas.bin
    volumes:
      - canvas_data:/data

  web:
    image: ne1i/pixels_site-web:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  canvas_data:
